version: '3.8'

services:

  app:
    build: .
    container_name: php-JMK
    volumes:
      - ./:/var/www/html
    networks:
      - JMK-network
    env_file:
      - .env


  web:
    image: nginx:latest
    container_name: nginx-web
    ports:
      - "8090:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    env_file:
      - .env
    networks:
      - JMK-network


networks:
  JMK-network:
    driver: bridge